### ISSUE TITLE
Project doesn't compile

### ISSUE THREAD

**Issue by irevoire** [smarr/ReBenchDB#173]
Hey, when I run `npm run compile` on [the latest commit](https://github.com/smarr/ReBenchDB/commit/1245e6bdd20bc0fe9b630fafe5e4ccd27512a8dd) of the `main` branch it throws these errors;
![image](https://github.com/smarr/ReBenchDB/assets/7032172/c2d538e8-2df4-4e01-9f64-4834233485e8)

I don't think it's especially related to my setup or node version, as running `docker build .` doesn't work either with pretty much the same errors:
```
Step 20/21 : RUN npm run compile
 ---> Running in f376d9c777c4

> rebenchdb@0.3.0 precompile
> npm run prep-folders && npm run compile-uplot


> rebenchdb@0.3.0 prep-folders
> mkdir -p tmp/interm tmp/knit resources/reports resources/exp-data


> rebenchdb@0.3.0 compile-uplot
> terser --module --ecma 2018 --compress --mangle -o ./resources/uPlot.esm.min.js -- node_modules/uplot/dist/uPlot.esm.js


> rebenchdb@0.3.0 compile
> tsc

src/backend/compare/compare.ts(165,56): error TS2339: Property 'body' does not exist on type 'Request'.
src/backend/compare/compare.ts(230,19): error TS2339: Property 'body' does not exist on type 'Request'.
src/backend/github/github.ts(18,55): error TS2339: Property 'body' does not exist on type 'Request'.
src/backend/rebench/results.ts(31,49): error TS2339: Property 'body' does not exist on type 'Request'.
The command '/bin/sh -c npm run compile' returned a non-zero code: 2
```

**Comment by smarr** [comment]
Hi @irevoire, thanks for reaching out.

Have you tried a full `npm install .`?

I just tried the following on a Ubuntu and macOS, it seems to succeed:

```
git clone --depth 1 https://github.com/smarr/rebenchdb
cd rebenchdb
npm install .
```

**Comment by irevoire** [comment]
Sadly, no, I get the same error as before :pensive: 
![image](https://github.com/smarr/ReBenchDB/assets/7032172/aed97270-4441-4c49-8ce5-9db6f365e4ac)

I'm running on arch, though, and since there are no dependencies specified, I was lowkey expecting something like that.
But I thought it would work with docker build

**Comment by smarr** [comment]
What version of npm/node are you using?

I am having here npm 9.8.0 + node v20.5.1 and npm 9.9.2 + v19.9.0.

**Comment by smarr** [comment]
And just to be sure, the installation of the dependencies from `package.json`/`package-lock.json` worked without issues?

**Comment by irevoire** [comment]
> What version of npm/node are you using?

Ooh yes, funny, it looks like I got a very outdated version for both npm and node (even though I just installed both of them like one hour ago)
```
% npm --version
6.14.15
% node --version
v14.18.0
```

> And just to be sure, the installation of the dependencies from package.json/package-lock.json worked without issues?

Honestly, I don't know how anything works in the js/ts ecosystem; I think it worked but cannot guarantee it.
The only error I encountered was the one I showed you, and I think the dependencies were gathered at the very beginning of the process, so I would say yes.


-----

After updating npm + node with nvm, it worked, and I was even able to run `docker build .` thanks!
I don't know if there is a way to specify the minimum required version of node or npm, but that would be nice.

And isn't it strange that docker seems to use _my_ npm install instead of using the one we know that works? :thinking:

**Comment by smarr** [comment]
> I don't know if there is a way to specify the minimum required version of node or npm, but that would be nice.

I believe I do exactly that here:
https://github.com/smarr/ReBenchDB/blob/master/package.json#L31-L33

But, that might not be backwards compatible and a more recent thing than the versions you got 😄 
And in the case of Docker, it's even more odd indeed. The Dockerfile says it is using `postgres:16-bookworm`, which I would hope implies a certain minimum version. Hm, well, [looking at it](https://packages.debian.org/bookworm/nodejs), Bookworm comes with v18.19, which is lower than what I say I required hmmm...

**Comment by irevoire** [comment]
>  I don't know if there is a way to specify the minimum required version of node or npm, but that would be nice.

Looks like there is, and you already did what you were supposed to do here https://github.com/smarr/ReBenchDB/blob/master/package.json#L31-L33

Theoretically, from what I see, the only thing missing is the `.npmrc`; https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json

But I tried to set it, and it didn't work either in my tests, so I have no idea of what you should do ahah

**Comment by smarr** [comment]
I spent some time on moving to Docker compose, maybe you could give #175 a try?

**Comment by irevoire** [comment]
Hey! Yeah, sorry, I'm not at home right now; I'll definitely give it a try on Monday and keep you up

**Comment by smarr** [comment]
No hurry :)

**Comment by irevoire** [comment]
The docker-compose did work.

Closing the issue :+1:

**Comment by smarr** [comment]
Oh, good. Thanks for trying!
